% Solve a Clustering Problem with a Self-Organizing Map
% Script generated by NCTOOL
% Created Sun Feb 24 00:35:37 EET 2013
%
% This script assumes these variables are defined:
%
%   irisInputs - input data.
clear all;  close all;  clc;
load iris_dataset;

inputs = irisInputs;

% Create a Self-Organizing Map
dimension1 = 2;
dimension2 = 2;
net = selforgmap([dimension1 dimension2]);

% Train the Network
[net,tr] = train(net,inputs);

% Test the Network
yh = net(inputs);
cyh = vec2ind(yh);

y = irisTargets;
cy = vec2ind(y);

figure(1);  hold off;
plot(cyh, 'b-o');  hold on;    title('Predicted-cluster id');
plot(cy, 'r-*');               title('Actual Value');
legend('Clustered', 'Actual');
xlabel('Sample No');

% View the Network
% view(net)

% Plots
% Uncomment these lines to enable various plots.
%figure, plotsomtop(net)
%figure, plotsomnc(net)
%figure, plotsomnd(net)
%figure, plotsomplanes(net)
%figure, plotsomhits(net,inputs)
%figure, plotsompos(net,inputs)
